[build]
  # Build command for Astro
  command = "npm run build"
  
  # Publish directory (Astro's server output)
  publish = "dist"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# Functions for server-side rendering
[functions]
  directory = "dist/functions"

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
